### ISSUE TITLE
Can't load video from assets

### ISSUE THREAD

**Issue by matthew-carroll** [ollydixon/flutter_macos_video_player#11]
I'm trying to use this video player in a presentation app, similar to Powerpoint or Keynote.

I have videos packaged with my app assets that I'd like to play in the presentation. However, `VideoPlayerController.asset("...")` triggers an unimplemented error when `initialize()`ing.

Code:
```dart
_videoPlayerController = VideoPlayerController.asset("assets/content/demo_graph-paper.mov");
await _videoPlayerController.initialize();
_videoPlayerController.play();
```

Error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(video_player, not implemented, null, null)
#0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:189:7)
<asynchronous suspension>
#1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:53:37)
<asynchronous suspension>
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:363:19)
<asynchronous suspension>
#3      _PresentationState._setupVideoPlayer (package:presentations/main.dart:88:5)
<asynchronous suspension>
```

**Comment by kekko7072** [comment]
+1

**Comment by MinuteReversal** [comment]
+1

**Comment by ollydixon** [comment]
Unfortunately don’t have time to fix this. I though by now Flutter would have a video player!

open to PR requests though ☺️

**Comment by srix55** [comment]
Flutter seems to be waiting for the platform-view feature for desktop. Not sure what the progress is.

**Comment by ollydixon** [comment]
They've been working on that for a long time.

**Comment by cbenhagen** [comment]
This depends on https://github.com/flutter/flutter/issues/47681 which hopefully will soon be fixed by https://github.com/flutter/engine/pull/37421.
