### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(video_player, not implemented, null, null)

### ISSUE THREAD

**Issue by bullets-jyr** [ollydixon/flutter_macos_video_player#20]
This is the error log that is confirmed when building on macOS. how can i solve it? I'm using macOS Ventura 13.3.1.

Debug service listening on ws://127.0.0.1:57589/PtUgE77eblw=/ws
Syncing files to device macOS...
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(video_player, not implemented, null, null)
#0      VideoPlayerMacOsApi.create (package:video_player_macos/src/messages.g.dart:298:7)
<asynchronous suspension>
#1      VideoPlayerMacOs.create (package:video_player_macos/src/video_player_macos.dart:65:37)
<asynchronous suspension>
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:404:19)
<asynchronous suspension>
#3      _HomeScreenState.initializeVideoPlayerController (package:vid_player_macos/screen/home_screen.dart:23:5)
<asynchronous suspension>

**Comment by bullets-jiyoungryu** [comment]
This is the error log that is confirmed when building on macOS. how can i solve it? I'm using macOS Ventura 13.3.1.

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  VideoPlayerController? videoPlayerController;

  @override
  void initState() {
    super.initState();

    initializeVideoPlayerController();
  }

  initializeVideoPlayerController() async {
    videoPlayerController = VideoPlayerController.asset('assets/videos/sample.mp4');
    await videoPlayerController!.initialize();
    setState(() {

    });
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        videoPlayerController!.play();
      },
      child: VideoPlayer(
        videoPlayerController!,
      ),
    );
  }
}

**Comment by bullets-jiyoungryu** [comment]
I'm looking forward to playing the sample.mp4 video in the videos folder under the assets folder in my macOS desktop app. Is there something wrong with my code?
VideoPlayerController.asset('assets/videos/sample.mp4');

**Comment by nikage** [comment]
@Bullets-jyr I had similar problem. What I've figured out is if something is wrong with your asset(invalid path/no acess rights/not listed in pubspec etc) it throws the deceiving error. I should throw smth like "Failed to init asset" or whatever.
https://github.com/ollyde/flutter_macos_video_player/blob/5842c6c8f26017fa27d8baa216cb0f3e977dde66/packages/video_player/video_player_macos/macos/Classes/FLTVideoPlayerPlugin.m#L566-L571

When I tried to use FilePicker it worked fine.
